# Generated by Django 5.0.6 on 2024-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
